//! Which gated suites did **not** run, said where a plain `cargo test` will actually see it — and,
//! on demand, a reason to fail instead of skip.
//!
//! Every gated suite in this repository already detected its own prerequisite and, finding it
//! absent, printed a line and returned `Ok(())`. Nothing was wrong with the detection; the problem
//! was everything after it. `eprintln!` inside a `#[test]` goes through libtest's **output
//! capture**, which prints a test's output only when that test *fails* — so a skip's explanation
//! was written to a buffer that a passing run throws away. `86 passed` and eight suites that never
//! ran looked identical, and the only difference an operator could observe was how long the binary
//! took (issue #112).
//!
//! So this module is not a second gate. Each suite keeps the check it always had; what changed is
//! that the branch it takes on failure funnels through [`skip`], which does three things the
//! scattered `eprintln!`s could not:
//!
//! 1. **Writes where a passing run can see it.** [`std::io::Stderr`]'s `Write` impl goes to the
//!    process's real fd 2. libtest's capture intercepts the `print!`/`eprintln!` *macros* — they
//!    route through `std::io::_eprint`, which diverts to a thread-local buffer — and it does not
//!    intercept a direct write to the handle. That distinction is the whole mechanism here: it is
//!    why the report survives a green run and why the `eprintln!`s it replaces did not.
//! 2. **Deduplicates.** A suite with six gated tests reported six times; the report is one line per
//!    suite, whichever of its tests reaches the gate first.
//! 3. **Can refuse.** With [`REQUIRE_GATED_ENV`] present, a skip of an enforced prerequisite
//!    panics, and libtest turns that into a failed test named after the suite that could not run.
//!
//! # No end-of-run summary, and that is libtest's constraint rather than a choice
//!
//! The report is streamed — a header, then a line per suite as each one reaches its gate — instead
//! of being batched into a block at the end. There is no hook to batch it into: with
//! `harness = true` the test binary's `main` is generated by rustc and the user's `main` is dead
//! code, statics are never dropped, and libtest calls `process::exit` on the failing path, which
//! skips what thread-local destructors would otherwise run. A trailing summary would need either a
//! custom harness (a new dependency, on a workspace with a hard one-version wall) or a wrapper
//! script (which `cargo test` would not go through). The header therefore carries the part that has
//! to be read — *these results do not cover everything* — rather than a count that has to wait.
//!
//! # Compiled into both test targets
//!
//! `distributed_cluster` is a separate target for the reasons `tests/integration/main.rs` gives,
//! and it is also a suite that silently skips, so it includes this file by `#[path]`. One process
//! is one report: each binary keeps its own [`REPORTED`] set and prints its own header.
//!
//! Two consequences, both deliberate. The unit tests below run in **both** binaries — five pure
//! assertions, microseconds, and what keeps every constant here reachable from both crate roots, so
//! no `#[allow(dead_code)]` is needed to paper over the half each target does not use. And a
//! prerequisite added for one target is visible to the other, which is the point: the format and
//! the switch stay one rule rather than two that drift.

use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::io::Write;
use std::sync::{LazyLock, Mutex};

/// Environment variable by which a **run** asserts that its gated suites really ran.
///
/// **Presence is the assertion; the value is never read.** Absent, a missing prerequisite is a
/// reported skip and the run stays green — which is what keeps `cargo test` on a laptop with no
/// Postgres and no Docker passing, the same bargain CLAUDE.md strikes for `cargo run`. Present with
/// *any* value, including the empty string, and a skip of an enforced prerequisite
/// ([`Prerequisite::enforced`]) becomes a failed test.
///
/// # Why presence and not `=1`
///
/// This is deliberately the same rule, spelled the same way, as
/// [`lldb_qe_core::auth::REQUIRE_FLEET_TOKEN_ENV`] — read that first; the argument there is the
/// argument here. A `=1` switch is disarmed by *emptying* the variable, and emptying a variable is
/// exactly the edit an environment makes to it: a CI job that stops exporting a value, a compose
/// file that injects `FOO=` for an unset secret. The guard would then be defeated by the same class
/// of edit it exists to catch, and — worse for a *test* switch — it would go quiet rather than
/// loud. With presence as the assertion, blanking it leaves enforcement in force and weakening it
/// means **deleting** the variable, which is a structural diff in `ci.yml` rather than a value
/// nobody diffs.
///
/// Two switches in one repository that look alike must behave alike, or the next reader learns the
/// wrong rule from whichever they happen to read first. Do not "improve" either into a parsed
/// `1`/`true`/`yes`. Parsing the value is the bug.
///
/// Read with [`std::env::var_os`] and never `var`: `var` returns `Err` for a value that is not
/// UTF-8, and `.ok()` on that would turn a *present* variable into an absent one — disarming the
/// switch by way of the thing it must not inspect.
pub const REQUIRE_GATED_ENV: &str = "LLDB_TEST_REQUIRE_GATED";

/// Something a gated suite needs from outside the process, and what to do about not having it.
pub struct Prerequisite {
    /// What is missing, as the report names it.
    pub what: &'static str,
    /// How to supply it.
    pub how: &'static str,
    /// Whether [`REQUIRE_GATED_ENV`] turns a skip for want of this into a failure.
    ///
    /// Scoped rather than blanket, because the switch has exactly one intended setter — CI's
    /// `check` job — and a job cannot be made strict about a prerequisite it has no way to
    /// provide. See each constant below for which side of that line it is on and why.
    pub enforced: bool,
}

/// A Postgres the control-plane suites can migrate and write to.
///
/// **Enforced.** CI's `check` job runs a `postgres:18.4-alpine` service and passes its URL, so this
/// is precisely the prerequisite that job can guarantee — and the one whose silent skip issue #112
/// was filed about.
pub const SERVICES_DB: Prerequisite = Prerequisite {
    what: "a reachable Postgres services database",
    how: "set LLDB_TEST_POSTGRES_URL=postgres://…, or LLDB_DOCKER=1 with a Docker daemon running",
    enforced: true,
};

/// Generated TPC-H parquet in the working tree.
///
/// **Not enforced.** SF1 is about a gigabyte of parquet generated by `tpchgen-cli`; CI generates
/// none of it in any job, so a run that made this fatal would fail the `check` job for a reason
/// that job cannot fix. It is still reported — a suite that did not run is a suite that did not
/// run, whatever the reason — and a local switch that made *this* strict is a separate decision
/// with a separate variable, not a widening of this one.
pub const TPCH_DATA: Prerequisite = Prerequisite {
    what: "generated TPC-H parquet under data/",
    how: "run ./scripts/bootstrap.sh (or: tpchgen-cli -s 1 --format=parquet --output-dir data/sf1)",
    enforced: false,
};

/// A Docker daemon and the cluster image, for the cross-container smoke test.
///
/// **Not enforced**, for the same shape of reason as [`TPCH_DATA`] and one more: the only CI job
/// with a built image is `docker-cluster`, and it is a *different* job from the one with the
/// Postgres service. The strict switch is set on the job that has the database; making it strict
/// about this would fail that job for want of an image it never builds.
pub const DOCKER_CLUSTER: Prerequisite = Prerequisite {
    what: "a Docker daemon and the cluster image",
    how: "set LLDB_DOCKER=1 (CI's cross-container job also sets LLDB_IMAGE to a prebuilt tag)",
    enforced: false,
};

/// Whether a skip for want of `prerequisite` must be a failure instead, as a pure function of the
/// switch.
///
/// `required` is [`std::env::var_os`]'s answer for [`REQUIRE_GATED_ENV`]: `Some` when the variable
/// is **present**, whatever it holds — the argument's contents are deliberately never inspected.
///
/// Pure, and that is a testability requirement rather than a style preference. `std::env::set_var`
/// is `unsafe` in edition 2024 and `tests/integration/main.rs` makes "no test in this binary
/// mutates the environment" a standing rule that the ambient fleet auth's `OnceLock` depends on. A
/// policy reachable only through `std::env` would be a policy nothing in this binary could test —
/// which is the defect this whole module exists to close, reintroduced one level down.
pub fn is_fatal(prerequisite: &Prerequisite, required: Option<&OsStr>) -> bool {
    prerequisite.enforced && required.is_some()
}

/// `suite` is not running, because `prerequisite` is absent. Report it — or refuse.
///
/// Call it from the branch the suite already took when its check failed, and then return as
/// before. Under [`REQUIRE_GATED_ENV`] it panics and never returns, which is how a test fails:
/// libtest names the failing test, so the suites that could not run are listed by the harness
/// itself rather than by anything this module has to print.
pub fn skip(suite: &str, prerequisite: &Prerequisite) {
    assert!(
        !is_fatal(prerequisite, std::env::var_os(REQUIRE_GATED_ENV).as_deref()),
        "{REQUIRE_GATED_ENV} is set, so this run asserts that every gated suite really runs — but \
         `{suite}` cannot: it needs {what}. Fix it by supplying the prerequisite: {how}. If this \
         run is genuinely meant to skip it, DELETE {REQUIRE_GATED_ENV} from the environment — \
         emptying that variable changes nothing, because its presence is the assertion.",
        what = prerequisite.what,
        how = prerequisite.how,
    );
    let mut reported = REPORTED.lock().unwrap_or_else(|poison| poison.into_inner());
    // Written while the lock is held, so two suites skipping concurrently cannot interleave a
    // header with a line or two lines with each other.
    emit(&announce(&mut reported, line_for(suite, prerequisite)));
}

/// One line per suite, already reported. Process-global on purpose: the point is one report per
/// *run*, and a run is a process.
///
/// `tests/integration/main.rs` requires every piece of process-global state in that binary to be
/// argued rather than assumed, and the argument for this one is that it is append-only, keyed by
/// the exact line, read by nothing but the duplicate check, and asserted on by no test. Which
/// entries it ends up holding is a pure function of which prerequisites are absent, and nothing in
/// that binary mutates the environment those are read from — so test order permutes the *order* of
/// the report's lines and nothing else about it.
static REPORTED: LazyLock<Mutex<BTreeSet<String>>> = LazyLock::new(Mutex::default);

/// The report's line for one skipped suite. Self-contained: these are interleaved with libtest's
/// own output, so a line that needed the header for context would routinely be read without it.
fn line_for(suite: &str, prerequisite: &Prerequisite) -> String {
    format!(
        "lldb-test: SKIPPED {suite} — wants {what}: {how}",
        what = prerequisite.what,
        how = prerequisite.how,
    )
}

/// What to write for `line`, given what has already been written: nothing if it is a repeat, the
/// header plus the line if it is the first of the run, the line alone otherwise.
///
/// Split out from [`skip`] so the deduplication and the header-once rule are testable without a
/// process-global, and without a unit test writing to the real stderr of whatever binary runs it.
fn announce(reported: &mut BTreeSet<String>, line: String) -> Vec<String> {
    if !reported.insert(line.clone()) {
        return Vec::new();
    }
    if reported.len() > 1 {
        return vec![line];
    }
    vec![
        "lldb-test: ── gated suites are SKIPPING — a green `test result: ok` below does NOT cover \
         them ──"
            .to_string(),
        format!(
            "lldb-test: ── set {REQUIRE_GATED_ENV} (present with any value, even empty) to turn \
             these skips into failures ──"
        ),
        line,
    ]
}

/// Write to the process's real stderr, around libtest's capture.
///
/// The capture is what makes a skip invisible: it intercepts the `eprintln!` macro (which routes
/// through `std::io::_eprint` and, under a test, into a per-thread buffer that is printed only for
/// a *failing* test) and it does not intercept a write to the [`std::io::Stderr`] handle. So this
/// is the one channel through which a passing test can say something.
///
/// Failures are swallowed rather than propagated: a report is not worth turning a green run red,
/// and stderr being unwritable is not something a test can act on.
fn emit(lines: &[String]) {
    if lines.is_empty() {
        return;
    }
    let mut stderr = std::io::stderr().lock();
    for line in lines {
        let _ = writeln!(stderr, "{line}");
    }
    let _ = stderr.flush();
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The property that separates this switch from the `=1` shape it deliberately is not: the
    /// edit most likely to be made to it — emptying it — must not disarm it.
    #[test]
    fn presence_is_the_assertion_whatever_the_value() {
        for value in ["", "0", "false", "no", "please do not"] {
            assert!(
                is_fatal(&SERVICES_DB, Some(OsStr::new(value))),
                "an enforced prerequisite must be fatal with {REQUIRE_GATED_ENV}={value:?} — the \
                 value is never parsed"
            );
        }
    }

    /// Absent is today's behaviour, and that is CLAUDE.md's rule rather than a preference:
    /// `cargo test` with no services must pass.
    #[test]
    fn absent_leaves_every_prerequisite_skippable() {
        for prerequisite in [&SERVICES_DB, &TPCH_DATA, &DOCKER_CLUSTER] {
            assert!(!is_fatal(prerequisite, None));
        }
    }

    /// The scoping CI depends on: the `check` job has a Postgres service and neither SF1 data nor
    /// a built image, so a switch that made those fatal would fail the only job that sets it.
    #[test]
    fn the_switch_covers_only_what_ci_can_supply() {
        let present = Some(OsStr::new(""));
        assert!(is_fatal(&SERVICES_DB, present));
        assert!(!is_fatal(&TPCH_DATA, present));
        assert!(!is_fatal(&DOCKER_CLUSTER, present));
    }

    /// A suite with several gated tests reports once, and the header precedes the first line only.
    #[test]
    fn the_report_is_one_line_per_suite_under_one_header() {
        let mut reported = BTreeSet::new();
        let first = announce(&mut reported, line_for("services_db", &SERVICES_DB));
        assert_eq!(
            first.len(),
            3,
            "header (two lines) then the suite: {first:?}"
        );
        assert!(first[0].contains("does NOT cover them"));
        assert!(first[1].contains(REQUIRE_GATED_ENV));
        assert!(first[2].contains("services_db"));

        let second = announce(&mut reported, line_for("query_reaper", &SERVICES_DB));
        assert_eq!(second.len(), 1, "no second header: {second:?}");
        assert!(second[0].contains("query_reaper"));

        let repeat = announce(&mut reported, line_for("services_db", &SERVICES_DB));
        assert!(repeat.is_empty(), "a suite reports once: {repeat:?}");
    }

    /// Each line stands alone, because libtest's own output is interleaved with these.
    #[test]
    fn a_line_names_the_suite_the_prerequisite_and_the_fix() {
        let line = line_for("tpch_baseline", &TPCH_DATA);
        assert!(line.contains("tpch_baseline"));
        assert!(line.contains(TPCH_DATA.what));
        assert!(line.contains(TPCH_DATA.how));
    }
}
